image: docker:latest

services:
  - docker:dind

stages:
  - build
  - upload

variables:
  UPLOAD_CONTAINER: $CI_REGISTRY/nextthingco/ci-tools:stable
  ARTIFACT_0: /opt/factory/factory.md5
  ARTIFACT_1: /opt/factory/factory.iso

build:
  stage: build
  script:
    - docker pull computermouth/sudeb
    - docker run --privileged -v $PWD:/opt/factory -w /opt/factory --rm computermouth/sudeb /bin/bash -c "sudo apt-get update -qq && sudo apt-get install -y live-build && sudo lb build"
    - pushd /opt/factory
    - ls -lsah
    - md5sum live-image-i386.hybrid.iso > factory.md5
    - mv live-image-i386.hybrid.iso > factory.iso
    - echo "UPLOAD!!!"
    - docker pull $UPLOAD_CONTAINER
    - docker run
      -e GHVAR_AWS_ID=${GHVAR_AWS_ID}
      -e GHVAR_AWS_PW=${GHVAR_AWS_PW}
      -e GHVAR_AWS_REGION=${GHVAR_AWS_REGION}
      -e CI_PROJECT_NAME=${CI_PROJECT_NAME}
      -e CI_BUILD_REF_NAME=${CI_BUILD_REF_SLUG}
      -e CI_BUILD_ID=${CI_BUILD_ID}
      -e ARTIFACT_0=${ARTIFACT_0}
      -e ARTIFACT_1=${ARTIFACT_1}
      --rm -v $PWD:/upload -w /upload
      $UPLOAD_CONTAINER ci-s3-upload
      ${ARTIFACT_0}
      ${ARTIFACT_1}
